name: Build and Push Docker Image to ECR

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials from OIDC
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::849276828792:role/GitHubActionsOIDCRole
          aws-region: ap-south-1

      - name: Ensure ECR repository exists
        run: |
          aws ecr describe-repositories --repository-names ccd-llt --region ap-south-1 || \
          aws ecr create-repository --repository-name ccd-llt --region ap-south-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region ap-south-1 | \
          docker login --username AWS --password-stdin 849276828792.dkr.ecr.ap-south-1.amazonaws.com

      - name: Build Docker image
        run: |
          docker build -t ccd-llt .

      - name: Tag Docker image
        run: |
          docker tag ccd-llt:latest 849276828792.dkr.ecr.ap-south-1.amazonaws.com/ccd-llt:latest

      - name: Push Docker image to Amazon ECR
        run: |
          docker push 849276828792.dkr.ecr.ap-south-1.amazonaws.com/ccd-llt:latest
